services:
  app:
    user: "0:0"
    image: etherpad/etherpad:latest
    tty: true
    stdin_open: true
    volumes:
      - plugins:/opt/etherpad-lite/src/plugin_packages
      - etherpad-var:/opt/etherpad-lite/var
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      ADMIN_PASSWORD: ${ETHERPAD_ADMIN_PASSWORD}
      DB_CHARSET: utf8mb4
      DB_HOST: postgres
      DB_NAME: ${POSTGRES_DB}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_PORT: 5432
      DB_TYPE: "postgres"
      DB_USER: ${POSTGRES_USER}
      DEFAULT_PAD_TEXT: "Welcome to Etherpad!"
      DISABLE_IP_LOGGING: false
      SOFFICE: null
      TRUST_PROXY: true
    restart: always
    ports:
      - "9001:9001"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

volumes:
  postgres_data:
  plugins:
  etherpad-var:
