services:
  app:
    user: "0:0"
    # image: etherpad/etherpad:latest
    image: platformht/etherpad:latest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - plugins:/opt/etherpad-lite/src/plugin_packages
      - etherpad-var:/opt/etherpad-lite/var
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      ADMIN_PASSWORD: ${{ secrets.ETHERPAD_ADMIN_PASSWORD }}
      DB_CHARSET: ${DOCKER_COMPOSE_APP_DB_CHARSET:-utf8mb4}
      DB_HOST: postgres
      DB_NAME: ${{ secrets.POSTGRES_DB }}
      DB_PASS: ${{ secrets.POSTGRES_PASSWORD }}
      DB_PORT: ${{ secrets.POSTGRES_PORT }}
      DB_TYPE: "postgres"
      DB_USER: ${{ secrets.POSTGRES_USER }}
      # For now, the env var DEFAULT_PAD_TEXT cannot be unset or empty; it seems to be mandatory in the latest version of etherpad
      DEFAULT_PAD_TEXT: "Bienvenue sur Etherpad!"
      DISABLE_IP_LOGGING: ${{ secrets.DISABLE_IP_LOGGING }}
      SOFFICE: ${DOCKER_COMPOSE_APP_SOFFICE:-null}
      TRUST_PROXY: ${DOCKER_COMPOSE_APP_TRUST_PROXY:-true}
    restart: always
    ports:
      - "9001:9001"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

volumes:
  postgres_data:
  plugins:
  etherpad-var:
